### ISSUE TITLE
Make snake velocity not FPS dependent

### ISSUE THREAD

**Issue by rzimmerdev** [courselab/snaskii22#100]
Regarding one of the "_TODOS_" left within the code, the snake's movement shouldn't be slow if the FPS were reduced, neither too fast so as to not allow the player to react to it.

I'll be implementing a system to correctly fix and control the snakes movement when dealing with floating point adjusts.
(This will also be useful for the Issue and PR #99

**Comment by rzimmerdev** [comment]
The main point for this Issue will be the need to deal with float divisions (resulting from dividing and multiplying the FPS value by the Snakes default velocity)

**Comment by lmkobe** [comment]
This issue can be closed, right?
