### ISSUE TITLE
Font size impacting gameplay

### ISSUE THREAD

**Issue by Zoh-j02r** [courselab/snaskii22#106]
while running snaskii in my terminal I noticed the snake leaving from screen or the Movement/Commands title dissapearing. it happened  because of the font size specification.

**Comment by rzimmerdev** [comment]
This is expected behavior I suppose, no way to go around.
The best that can be done is to advise the user to use a recommended font size, or restrict the program to start when not using an adequate size.

**Comment by rzimmerdev** [comment]
If anyone else has an insight on this, I'm happy to work on any further solutions
