### ISSUE TITLE
make the snake move

### ISSUE THREAD

**Issue by Grillo-0** [courselab/snaskii22#18]
Currently the snake doesn't move at all. To start creating the game logic the first thing needed would be the snake movement.

**Comment by monacofj** [comment]
It'd be nice if we could use the arrow keys.

**Comment by vitorfrois** [comment]
We can use a queue (FILO) to represent the snake, where each element is a point in the game coordinates. When moving, pop the queue, add the point that represents the next step of the snake to it and update the screen with new coordinates.
If the point the snake landed is 'food', just doesnt pop the queue.

**Comment by vitorfrois** [comment]
@Grillo-0 please check my last commit on feature/#18/movesnake branch.

**Comment by Grillo-0** [comment]
> @Grillo-0 please check my last commit on feature/#18/movesnake branch.

I wil check. I aso made a branch too a wile a go, I'm gone push it now

**Comment by Grillo-0** [comment]
> We can use a queue (FILO) to represent the snake, where each element is a point in the game coordinates. When moving, pop the queue, add the point that represents the next step of the snake to it and update the screen with new coordinates. If the point the snake landed is 'food', just doesnt pop the queue.

Yeah i'm using this method in my implementation

**Comment by vrrusso** [comment]
I see this issue need help. Can I help it? One think to thought is if the snake should collide with the borders, or connect with the other side of the screen.

**Comment by reynaldocoronatto** [comment]
@vrrusso according to the README description of the game, if the snake touches any border it should die because the borders are electrified.

**Comment by vitorfrois** [comment]
the snake moves! (theoretically)
we need to update the screen to test and confirm
