### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by mairacanal** [courselab/snaskii22#24]
Currently, the repository has unused files that could be removed, such as:

- [TODO](https://github.com/courselab/snaskii22/blob/main/TODO):  the organization of the task and future of the project is held through issues, so the TODO file is not necessary
- [CONTRIBUTING.md.backup](https://github.com/courselab/snaskii22/blob/main/doc/CONTRIBUTING.md.backup): backup files don't belong in the repository
- [CONTRIBUTING.md~](https://github.com/courselab/snaskii22/blob/main/doc/CONTRIBUTING.md%7E): same as above
- [README](https://github.com/courselab/snaskii22/blob/main/README): a symbolic link to the README is redundant

**Comment by vrrusso** [comment]
I think this is a good idea, as it improve readability of the project!

**Comment by mafemello** [comment]
Agreed! It would be easier to find really important informations and start collaborating.
