### ISSUE TITLE
Add sudo command in the install section of README

### ISSUE THREAD

**Issue by PauloMRocha** [courselab/snaskii22#36]
Please add `sudo` command before `make install` in README.md file. To install the game super user permission is needed.

**Comment by monacofj** [comment]
Well, user may want to install elseware with `configure --prefix=$(HOME)`.
Perhaps README should offer this possibility and warn that superuser permission is necessary to install systemwide?

**Comment by gp2112** [comment]
I don't think this is necessary. It will depends on your distribution. The one I'm using [NixOS], for example, installs, for default, in a separated environment. So it doesn't need superuser permissions for `make install`, even without a explicit prefix.

**Comment by PauloMRocha** [comment]
It makes sense, I will close the issue then. Thanks for the help.
