### ISSUE TITLE
Create a better mechanisms to draw on screen

### ISSUE THREAD

**Issue by Grillo-0** [courselab/snaskii22#37]
As for now to draw on the screen you have a single buffer to write on it. 
It would be nice if we have a background and a foreground layer. So you could write the same background and just change the foreground layer.
This would benefit the drawing implementation of the snake, because it would be easy to remove the drawing of the past frame by just changing the foreground layer.

**Comment by vrrusso** [comment]
Hey I was reviewing this issue, I would like to contribute aiming at make snake movement possible, but I have some doubts about ncurses ... what would be the appropriate space to ask and to contribute to this issue?
