### ISSUE TITLE
Add support to nix shell

### ISSUE THREAD

**Issue by Math-42** [courselab/snaskii22#5]
Add support for an ephemeral nix shell, containing all dependencies needed to build and run.

**Comment by monacofj** [comment]
Libncurses should work with any POSIX-compliant shell, as far as I (loosely) know.
Isn't working with some particular shell?
Could  you describe the limitations?

**Comment by gp2112** [comment]
> Libncurses should work with any POSIX-compliant shell, as far as I (loosely) know. Isn't working with some particular shell? Could you describe the limitations?

@monacofj nix-shell is, actually, a isolated environment for development. You can locally install everything you need to build the program just executing `nix-shell` if you have [nix](nixos.org) installed :)

**Comment by monacofj** [comment]
Thanks for the elucidations!
