### ISSUE TITLE
Add a .editorconfig file

### ISSUE THREAD

**Issue by Math-42** [courselab/snaskii22#59]
[editorconfig](https://editorconfig.org/) is a file format that defines how the editor should work for this project, setting how the project indentation should be done, number of tabs, line at the end of the document, etc.

It could only contain an initial suggestion to later be changed as the community decides. Several editors already have native support or an extension for this file type.

Related to #58 #13 and #9.

**Comment by lmkobe** [comment]
Closed by #64
