### ISSUE TITLE
Add ultils.c to Makefile.am

### ISSUE THREAD

**Issue by Grillo-0** [courselab/snaskii22#66]
On the conversion made on #63 the `utils.c` was left out of the `snaskii_bin_SOURCES`. This is not correct as all the translation units need to be on this variable

**Comment by pedrolmcastro** [comment]
Actually, I think `utils.c` should not exist any more, if you look at `utils.h` there is only a macro, no function header or extern variable to live in a translation unit of its own, the correct thing would be to rm the file since there is no need for it anymore

**Comment by Grillo-0** [comment]
> Actually, I think `utils.c` should not exist any more, if you look at `utils.h` there is only a macro, no function header or extern variable to live in a translation unit of its own, the correct thing would be to rm the file since there is no need for it anymore

Oh I see, you moved the code made on utils.c to times.c, so yeah, I too think the utils.c should be deleted. Closing this issue and creating another issue now :)
